
user:
  username: belong
#  端口
server:
  port: 8080
#  FreeMarker配置
spring:
  freemarker:
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/

  #  数据源
  datasource:
    name: video
    url: jdbc:mysql://127.0.0.1:3306/video?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root

    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    midIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20



